- shell: mkdir -p /data/gitbucket
- shell: chown -R 1000:1000 /data/gitbucket
- shell: mkdir -p /var/jenkins_home/
- shell: chown -R 1000:1000 /var/jenkins_home
- shell:-↲
    cmd: | 
cat > docker-compose.yml << EOF
version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
   volumes:
      - /var/jenkins_home:/var/jenkins_home
#     - ./src/html:/var/www/html
#   depends_on:
#       - php
    restart: always

  gitbucket:
    image: gitbucket/gitbucket
    restart: always
    ports:
      - 8081:8080
      - 29418:29418
    volumes:
      - /data/gitbucket:/gitbucket
#    depends_on:
#      - db
#    environment:
#      - GITBUCKET_DB_URL=jdbc:postgresql://db/gitbucket
#      - GITBUCKET_DB_USER=gitbucket
#      - GITBUCKET_DB_PASSWORD=gitbucket
#    command: ["/gitbucket/wait-for-it.sh", "db:5432", "--", "java", "-jar", "/opt/gitbucket.war"]
EOF
