---
# tasks file for nginx
#
- name: UnInstall apache
  yum:
    name: httpd
    state: absent
- shell: 
    cmd: |
        cat > /etc/yum.repos.d/nginx.repo << NGINX
        [nginx]
        name=nginx repo
        baseurl=http://nginx.org/packages/centos/7/\$basearch/
        gpgcheck=0
        enabled=1
        NGINX
- name: Install nginx
  yum:
    name: nginx
    state: present
- name: Install nginx
  yum:
    name:
      - nginx
    state: present
- shell: cp -p /etc/nginx/conf.d/default.conf{,.`date +%Y%m%d_%s`}
  register: nginx_conf
  ignore_errors: True
- shell: 
    cmd: |
        cat > /etc/nginx/conf.d/default.conf << NGINX
        server {
            listen       *:80;
            server_name  localhost;
        
            #charset koi8-r;
            access_log  /var/log/nginx/xxxxx-access.log  main;
            error_log   /var/log/nginx/xxxxx-error.log;
            root   /var/www/xxxxx/webroot;
            index  index.php index.html index.htm;
            location / {
                try_files \$uri \$uri?\$args \$uri/ /index.php?\$uri&\$args /index.php?\$args;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
            location ~ \.php\$ {
                try_files \$uri =404;
                fastcgi_pass   unix:/var/run/php-fpm/php-fpm.sock;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  \$document_root\$fastcgi_script_name;
                fastcgi_param  CAKEPHP_ENV 'local';
                fastcgi_read_timeout 120;
                include        fastcgi_params;
            }
            location = /favicon.ico {
                error_page    404 = @favicon;
                access_log    off;
                log_not_found off;
            }
            location @favicon {
                empty_gif;
                access_log    off;
                log_not_found off;
            }
        }
        NGINX
- shell: cp -p /etc/nginx/nginx.conf{,.`date +%Y%m%d_%s`}
  register: nginx_conf
  ignore_errors: True
- shell: sed -i 's/sendfile.*/sendfile off;/' /etc/nginx/nginx.conf
- shell: mkdir -p /var/cache/nginx/.composer
- shell: chown -R nginx. /var/cache/nginx/.composer
- shell: systemctl enable nginx
- shell: setenforce 0
- shell: systemctl start nginx
